# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODWork/MY_MCCPU_SOC/MY_MCCPU_SOC.srcs/sources_1/ip/dmem/dmem.xci
# IP: The module: 'dmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODWork/MY_MCCPU_SOC/MY_MCCPU_SOC.srcs/sources_1/ip/dmem/dmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CODWork/MY_MCCPU_SOC/MY_MCCPU_SOC.srcs/sources_1/ip/dmem/dmem.xci
# IP: The module: 'dmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODWork/MY_MCCPU_SOC/MY_MCCPU_SOC.srcs/sources_1/ip/dmem/dmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
